-- Seeds exactly two PolicyVersion rows so the consent flow has something to
-- reference (MVP-020, FR-004). This is metadata about a version only — an
-- opaque version identifier and an effective date — never the operative
-- legal text (docs/final-decisions.md, "MVP-020 open questions 46, 47 and
-- 48", question 5: no policy copy is authored or generated by the agent;
-- PolicyVersion has no text column at all). The version string below is a
-- clearly marked placeholder, not a real, reviewed policy version, and must
-- be replaced by the product owner before this surface is used for real.

INSERT INTO "policy_versions" ("id", "documentType", "version", "effectiveAt", "createdAt") VALUES
  ('policy-tos-placeholder-v1', 'TERMS_OF_SERVICE', 'placeholder-pending-product-owner-review', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('policy-privacy-placeholder-v1', 'PRIVACY_POLICY', 'placeholder-pending-product-owner-review', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
